apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-01
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: kubernetes.io/hostname, operator: In ,values: ["controlplane"]}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-01
spec:
  accessModes:
    - ReadWriteOnces
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual    # point to pv file storageclassname 

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-04
spec:
  containers:
    - name: con-01
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: my-vol-01
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-vol-01
      persistentVolumeClaim:
        claimName: my-pvc-01




  

